### ISSUE TITLE
Order of `list-all`

### ISSUE THREAD

**Issue by NobbZ** [HashNuke/asdf#33]
While setting up my environment, I realised that the `erlang` and `elixir` plugin do list the available versions from newest to oldest, while `nodejs` does it from oldest to newest.

There should be either a "filter" in asdf which does sorts all the version into a specific order, or a requirement to the plugins to list the versions in a particular order.

I'd prefer to see the most recent version as the last item, such that one can see the most recent version of something even in unscrollable environments.

**Comment by Stratus3D** [comment]
Right now I believe list-all calls the `list-all` script in the plugin's bin directory. I suppose asdf could capture that output and sort it, but I think this would be likely to cause other problems as some plugins may need to handle odd cases. For example, the Erlang versioning scheme changed several versions back, from the old R16B02 format to the new semantic versioning (18.2.1). `sort` would not be able to properly sort all the Erlang versions. I think it's best to leave sorting up to the plugins, since they can handle the odd scenarios in the version numbers. 

We can't really enforce a "requirement" since anyone can create plugins and publish them on GitHub for others to use. It would probably be a good idea to have a convention for version ordering. @HashNuke what do you think? Perhaps we should come up with a convention for version sorting and mention it on the plugin creation page?

**Comment by NobbZ** [comment]
I am aware of the fact that sorting using `sort` might be hard, especially because of Erlang version numbering scheme ;)

And by saying "require plugin maintainers to sort in a certain order" I did mean a soft requirement, since I do know it might be hard to enforce it.

**Comment by HashNuke** [comment]
@NobbZ We'll change the nodejs plugin to list the latest first. The idea is to be able to get "see" the latest version quickly.

**Comment by NobbZ** [comment]
That's why I do prefer latest last, I don't have to search the start of the
output, but can read the line right above the prompt. Also when I know the
list will be long, I have to use head to avoid scrolling, while I can just
let it go when latest is last.

Akash Manohar <notifications@github.com> schrieb am Sa., 12. März 2016
16:53:

**Comment by HashNuke** [comment]
@NobbZ Ah yes makes sense. Will make changes.

**Comment by HashNuke** [comment]
Changes made ~!

**Comment by HashNuke** [comment]
@Stratus3D yes. We should mention the version ordering on the plugin creation page as oldest-first.

**Comment by pvinis** [comment]
I guess related to this, is that `nodejs` gives me this:
```
nodejs
  10.15.1
  11.15.0
  12.17.0
  14.13.1
  15.3.0
  8.17.0
```

I would like to have 8 at te top of the list. Now it's not really correct, it's alphabetical.
